name: Clone Repo into Databricks

on:
  push:
    branches:
      - main  # Triggers the workflow on push or pull request events but only for the main branch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Databricks CLI
      run: |
        pip install databricks-cli

    - name: Prepare temporary directory
      run: |
        mkdir -p $RUNNER_TEMP/tempdir && rm -rf $RUNNER_TEMP/tempdir/*  # Ensure tempdir exists and is empty
        rsync -av --progress . $RUNNER_TEMP/tempdir --exclude .git  # Exclude .git directory

    - name: Clone Repo into Databricks
      env:
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      run: |
        databricks configure --token --host ${{ secrets.DATABRICKS_HOST }}
        databricks workspace rm /Users/myuser/mydir --recursive  # Delete existing directory
        databricks workspace import_dir $RUNNER_TEMP/tempdir /dev/  # Replace with your desired directory path
