name: Run Unit Tests in Databricks

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Databricks CLI
        run: |
          pip install databricks-cli

      - name: Create Databricks job
        run: |
          export DATABRICKS_HOST=${{ secrets.DATABRICKS_HOST }} # Replace with your Databricks workspace hostname
          export DATABRICKS_TOKEN=${{ secrets.DATABRICKS_TOKEN }}
          databricks jobs create --json "$(cat job_payload.json)" --python-version 3

      - name: Run unit tests in Databricks
        run: |
          export DATABRICKS_HOST=<databricks-host>  # Replace with your Databricks workspace hostname
          export DATABRICKS_TOKEN=${{ secrets.DATABRICKS_TOKEN }}
          job_id=$(databricks jobs list --output JSON | jq -r '.jobs[] | select(.settings.name=="Unit Tests Job") | .job_id')
          databricks jobs run-now --job-id $job_id
