name: Run Spark Unit Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Databricks CLI
        run: |
          pip install databricks-cli

      - name: Copy test files
        run: |
          cp main.py $GITHUB_WORKSPACE/code.py
          cp test_main.py $GITHUB_WORKSPACE/test.py

      - name: Create Databricks job
        run: |
          databricks jobs create --json "$(cat .github/workflows/job_payload.json)"

      - name: Run unit tests in Databricks
        run: |
          job_id=$(databricks jobs list --output JSON | jq -r '.jobs[] | select(.settings.name=="Unit Tests Job") | .job_id')
          databricks jobs run-now --job-id $job_id
