name: Run Unit Tests in Databricks

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Databricks CLI
        run: |
          pip install databricks-cli

      - name: Copy job_payload.json
        run: |
          cp job_payload.json .github/workflows/job_payload.json

      - name: Create Databricks job
        run: |
          export DATABRICKS_HOST=$DATABRICKS_HOST
          export DATABRICKS_TOKEN=${{ secrets.DATABRICKS_HOST }}
          databricks jobs create --json "$(cat .github/workflows/job_payload.json)"

      - name: Run unit tests in Databricks
        run: |
          export DATABRICKS_HOST=${{ secrets.DATABRICKS_HOST }}
          export DATABRICKS_TOKEN=${{ secrets.DATABRICKS_TOKEN }}
          job_id=$(databricks jobs list --output JSON | jq -r '.jobs[] | select(.settings.name=="Unit Tests Job") | .job_id')
          databricks jobs run-now --job-id $job_id
