name: Run Unit Tests in Databricks

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Databricks CLI
        uses: databrickslabs/github-actions/setup-databricks-cli@v0.3.1
        with:
          token: ${{ secrets.DATABRICKS_TOKEN }}

      - name: Run unit tests in Databricks
        run: |
          databricks jobs create --json "$(cat job_payload.json)" --python-version 3
          databricks jobs run-now --job-id <job-id>  # Replace with your Databricks job ID
