name: Run Spark Unit Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Databricks CLI
        run: |
          pip install databricks-cli


