name: Clone Repo into Databricks

on:
  push:
    branches:
      - main  # Triggers the workflow on push or pull request events but only for the main branch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Databricks CLI
      run: |
        pip install databricks-cli

    - name: Prepare temporary directory
      run: |
        mkdir -p tempdir && rm -rf tempdir/*  # Ensure tempdir exists and is empty
        rsync -av --progress . tempdir --exclude .git  # Exclude .git directory

    - name: Clone Repo into Databricks
      run: |
        echo ${{ secrets.DATABRICKS_TOKEN }} | databricks configure --token --host ${{ secrets.DATABRICKS_HOST }}
        databricks workspace import_dir -o tempdir /dev/  # Replace with your desired directory path
